class MAMT_AudioConfig:
    BASE_SR = 44100
    NFFT = 2048
    HOP = 512
    NMEL = 256

    MAIN_SECONDS = 2.048
    PAD_SECONDS = 0.256
    SEGMENT_SECONDS = MAIN_SECONDS + 2 * PAD_SECONDS
    STRIDE = MAIN_SECONDS / 2

    MAIN_SAMPLES = int(BASE_SR * MAIN_SECONDS)
    PAD_SAMPLES = int(BASE_SR * PAD_SECONDS)
    SEG_SAMPLES = int(BASE_SR * SEGMENT_SECONDS)
    STRIDE_SAMPLES = int(BASE_SR * STRIDE)
    N_FRAMES = 1 + int(SEG_SAMPLES / HOP)
    PAD_FRAMES = int(round(PAD_SECONDS * BASE_SR / HOP))